name: Infrastructure Deployment QA

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy: 
    name: Terraform settings
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Terraform Init
      run: terraform init
      working-directory: ./qa

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./qa

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./qa

     #- name: Terraform apply
     #  run: terraform apply
     #  working-directory: ./qa